apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading
  namespace: default
  labels:
    app: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading
  template:
    metadata:
      labels:
        app: trading
    spec:
      serviceAccountName: trading-service-account
      containers:
        - name: trading
          image: >-
            gcr.io/dexly-309412/trading@sha256:88600b09dab2e216259dcb831f16b5b01954f35e00ca40af9ed59c3513fb6c12
          imagePullPolicy: Always
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 1000m
          env:
            - name: CONFIG_LOGGING_FORMAT
              value: json
            - name: CONFIG_DATABASE_ADDRESS
              value: trading-database.default.svc.cluster.local
            - name: CONFIG_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: >-
                    postgres.trading-database.credentials.postgresql.acid.zalan.do
                  key: username
            - name: CONFIG_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: >-
                    postgres.trading-database.credentials.postgresql.acid.zalan.do
                  key: password
            - name: CONFIG_DATABASE_SSLMODE
              value: require
            - name: CONFIG_DATABASE_MIGRATIONDIR
              value: postgres/migration
            - name: CONFIG_PUBSUB_PROJECTID
              value: dexly-309412
            - name: CONFIG_PUBSUB_NOTIFICATIONSTOPICID
              value: dexly-notifications-topic
