apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-service
  namespace: default
  labels:
    app: trading-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-service
  template:
    metadata:
      labels:
        app: trading-service
    spec:
      containers:
        - name: trading-service
          image: >-
            gcr.io/dexly-309412/trading-service@sha256:1889f140d9b213a57e5385d1baac2a5a402270b6e5c3bcd6533734c6c9f8a770
          imagePullPolicy: Always
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 1000m
          env:
            - name: CONFIG_LOGGING_FORMAT
              value: json
            - name: CONFIG_DATABASE_ADDRESS
              value: trading-database.default.svc.cluster.local
            - name: CONFIG_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: >-
                    postgres.trading-database.credentials.postgresql.acid.zalan.do
                  key: username
            - name: CONFIG_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: >-
                    postgres.trading-database.credentials.postgresql.acid.zalan.do
                  key: password
            - name: CONFIG_DATABASE_SSLMODE
              value: require
            - name: CONFIG_DATABASE_MIGRATION
              value: 'true'
            - name: CONFIG_BINANCE_APIKEY
              valueFrom:
                secretKeyRef:
                  name: binance-config
                  key: apiKey
            - name: CONFIG_BINANCE_SECRETKEY
              valueFrom:
                secretKeyRef:
                  name: binance-config
                  key: secretKey
            - name: CONFIG_BINANCE_TESTNET
              valueFrom:
                secretKeyRef:
                  name: binance-config
                  key: testnet
            - name: CONFIG_BINANCE_PAIRS
              value: ETH/USDT
