name: trading-service

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
          with:
            go-version: 1.15.11

      - name: Build
        run: go build .

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
          with:
            go-version: 1.15.11

      - name: Test
        run: go test ./...

  publish:
    needs: test
    if: |
      (github.ref == 'refs/heads/master' && github.event_name == 'push')
        || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Setup Docker cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.GCR_REGISTRY_URL }}
          username: _json_key
          password: ${{ secrets.GCR_ADMIN_KEY }}

      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        env:
          IMAGE_NAME: 'dexly/trading-service'
          IMAGE_PREFIX: |
            ${{ secrets.GCR_REGISTRY_URL }}/${{ secrets.GCP_PROJECT_ID }}
        with:
          tags: ${{ env.IMAGE_PREFIX }}/${{ env.IMAGE_NAME }}
          push: true
